#!/usr/bin/env bash

set -e

export AWS_REGION=${AWS_REGION:-$AWS_DEFAULT_REGION}

: "${AWS_REGION:?Need to set AWS_REGION or AWS_DEFAULT_REGION}"
: "${AWS_ACCESS_KEY_ID:?Need to set AWS_ACCESS_KEY_ID}"
: "${AWS_SECRET_ACCESS_KEY:?Need to set AWS_SECRET_ACCESS_KEY}"

if (( $# < 2 )); then
  echo "usage: $(basename $0) cluster_name task_name[:revision] [command override]"
  echo "  runs the task in the cluster"
  exit 1
fi

cluster=$1; shift
task=$1; shift
commandArray=( "$@" )

msg="Running task $task on cluster $cluster"
cmd="aws ecs run-task --cluster $cluster --task-definition $task"

if (( ${#commandArray[@]} > 0 )); then
  json_file=$(mktemp -t overrides-XXXX.json)
  cat << EOF > $json_file
{
  "containerOverrides": [
    {
      "name": "$task",
      "command": $(printf '%s\n' "${commandArray[@]}" | jq -R . | jq -s .)
    }
  ]
}
EOF

  msg="$msg with command: ${commandArray[@]}"
  cmd="$cmd --overrides file://$json_file"
fi

echo $msg
$cmd
